import 'package:flutter/material.dart';

class HHString{ 
  static const String baseURL = "http://ec2-65-0-102-116.ap-south-1.compute.amazonaws.com:4000";
  static const String desc = 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. '
      '\n\nLorem Ipsum has been the industry\'s standard dummy. Lorem Ipsum is simply dummy text of the printing.'
      ' \n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy.';
  static const String hh = 'Heal@Home Programs';
  static const String pls_enter_reg_email = 'Please enter you registered email address. We will help you retrieve your password.';
  static const String terms = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';
  static const String programHeading = 'Alcohol Management Program';
  static const String program = "6 MONTH PROGRAM";
  static const String program_ = "Program";
  static const String proceed = "Proceed";
  static const String settings = "Settings";
  static const String enter_email = "Enter Email";
  static const String select_language = "Select Language";
  static const String change_password = "Change Password";
  static const String forgot_password = "Forgot Password";
  static const String reset_password = "Reset Password";
  static const String change_language = "Change Language";
  static const String emailExist = "Email already exist!";
  static const String emailExistDesc = "We found an account with this email, do you want to login?";
  static const String sample_ques = "Lorem Ipsum is simply dummy text of the printing and typesetting industry?";
  static const String feedbackTitle = "Feedback";
  static const String ABOUT_US = "ABOUT_US";
  static const String error = "Error";
  static const String submit = "Submit";
  static const String save = "save";
  static const String chat = "Chat";
  static const String mychat = "My Chats";
  static const String dashboard = "Dashboard";
  static const String no_msg = "No New Messages";
  static const String not_found = "Not Found";
  static const String not_data_found = "No Data Found";
  static const String my_programs = "My Programs";
  static const String please_share_thoughts = "Please share your thoughts with us";
  static const String please_contact_us = "Please use this form to connect us ";
  static const String please_enter_feedback = "Please enter a feedback";
  static const String please_enter_review = "Please enter your review";
  static const String no_record_found = "No Record Found";
  static const String schedule = "Schedule";
  static const String Upcoming = "Upcoming";
  static const String Completed = "Completed";
  static const String send = "Send";
  static const String no_up_sessions = "No Upcoming Sessions";
  static const String viewall = "View All";
  static const String drinking_diary = "Drinking Diary";
  static const String dailyjournaling = "Daily Journaling";
  static const String mysession = "My Session";
  static const String upcoming_sessions = "Upcoming Sessions";
  static const String Settings = "Settings";
  static const String search_pharma = "Search Nearest Pharmacies";
  static const String open = "Open";
  static const String cancel = "Cancel";
  static const String Notification = "Notification";
  static const String Notifications = "Notifications";
  static const String UpgradeNow = "Upgrade Now";
  static const String Journaling = "Journaling";
  static const String NewJournal = "New Journal";
  static const String oldJournal = "Old Journal";
  static const String Support = "Support";
  static const String home = "Home";
  static const String library = "Library";
  static const String assessment = "Assessment";
  static const String therapists = "Therapists";
  static const String address = "Address";
  static const String fname = "First Name";
  static const String lname = "Last Name";
  static const String name = "Name";
  static const String edit = "Edit";
  static const String submit_proceed = "Submit & Proceed";
  static const String phone_number = "Phone Number";
  static const String email = "Email";
  static const String Update = "Update";
  static const String share_reviews = "Share Your Reviews";
  static const String Questionaire = "Questionaire";
  static const String Profile = "Profile";
  static const String FAQ = "FAQ's";
  static const String edit_profile = "Edit Profile";
  static const String Contact_Us = "Contact Us";
  static const String more_info = "More Information";
  static const String about_us = "About Us";
  static const String tnc = "Terms & Conditions";
  static const String privacy = "Privacy Policy";
  static const String logout = "Log Out";
  static const String tems_condi = "Terms & Condition";
  static const String my_therapists = "My Therapists";
  static const String otp_verification = "OTP Verification";
  static const String resend_code = "Resend code in:";
  static const String Therapist = "Therapist";
  static const String Resend_OTP = "Resend OTP";
  static const String get_started = "Get Started";
  static const String Physician = "Physician";
  static const String case_manager = "Case manager";
  static const String reschedule = "Re-Schedule";
  static const String old_password = "Old Password";
  static const String new_password = "New Password";
  static const String confirm_password = "Confirm Password";
  static const String enter_msg = "Enter message";
  static const String confPasswordErrorMsg = "Please enter a confirm password";



  static const String token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTg3MDIyY2ViMWIzNWRlYjliNWQ4OSIsImlhdCI6MTYwOTU5NTA4MywiZXhwIjoxNjA5NjgxNDgzfQ.FqXJl58DJa1aSB2nOmNIDDuIctsGnQI5ChLTzpNgNEo";

}